name: Build
on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run Prettier
        run: |
          npx prettier --check .
      - name: Typecheck
        run: |
          npx tsc --noEmit
      - name:
        run: |
          npx jest --maxWorkers=4
      - name: Build
        run: |
          make sdist
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: ./*.tgz
